#!/usr/bin/env python3
"""
Parser for HohlbeinLab/OpenMicroscopy markdown files.

Converts the markdown tables in src/*.md into a single structured
docs/entries.json file that the static site (docs/index.html) reads.

Expected repo layout:
    OpenMicroscopy/
    ├── src/                  <- existing markdown source (untouched)
    ├── tools/
    │   └── parse.py          <- this script
    └── docs/                 <- GitHub Pages serves from here
        ├── index.html
        └── entries.json      <- generated by this script

Run from anywhere; paths are resolved relative to this file, not the
working directory:
    python3 tools/parse.py
"""

import json
import re
from pathlib import Path

import markdown
from bs4 import BeautifulSoup

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
OUT_DIR = REPO_ROOT / "docs"
OUT_DIR.mkdir(exist_ok=True)

# Map filenames -> (category label, slug)
CATEGORY_MAP = {
    "OM_Software.md": ("Software", "software"),
    "OM_Hardware.md": ("Hardware", "hardware"),
    "OM_Repositories.md": ("Repositories for data and protocols", "repositories"),
    "OM_Forums.md": ("Forums, learning resources & databases", "forums"),
    "OM_labs.md": ("Labs and people", "labs"),
}

CAD_FILE = "OM_CAD_tools.md"


def md_table_to_soup(md_text: str) -> BeautifulSoup:
    html = markdown.markdown(md_text, extensions=["tables"])
    return BeautifulSoup(html, "html.parser")


def clean_cell_links(cell) -> list:
    """Extract [label](url) style links from a table cell as structured dicts."""
    links = []
    for a in cell.find_all("a"):
        label = a.get_text(strip=True)
        href = a.get("href", "").strip()
        if href:
            links.append({"label": label or href, "url": href})
    return links


def cell_text(cell) -> str:
    return re.sub(r"\s+", " ", cell.get_text(" ", strip=True)).strip()


def parse_standard_file(path: Path, category_label: str, category_slug: str) -> list:
    text = path.read_text(encoding="utf-8")
    soup = md_table_to_soup(text)
    entries = []
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows[1:]:  # skip header row
            cells = row.find_all(["td", "th"])
            if len(cells) < 2:
                continue
            name = cell_text(cells[0]).strip("* ")
            if not name or name == "-":
                name = None
            description = cell_text(cells[1]) if len(cells) > 1 else ""
            links = clean_cell_links(cells[2]) if len(cells) > 2 else []
            if not links and len(cells) > 1:
                links = clean_cell_links(cells[1])

            if not name:
                name = (description[:40] + "…") if len(description) > 40 else description

            entries.append({
                "name": name,
                "description": description,
                "links": links,
                "category": category_label,
                "categorySlug": category_slug,
            })
    return entries


def parse_cad_file(path: Path) -> list:
    text = path.read_text(encoding="utf-8")
    soup = md_table_to_soup(text)
    entries = []
    for table in soup.find_all("table"):
        header_cells = table.find("tr").find_all(["th", "td"])
        headers = [cell_text(h) for h in header_cells]
        rows = table.find_all("tr")[1:]
        for row in rows:
            cells = row.find_all(["td", "th"])
            if not cells:
                continue
            values = [cell_text(c) for c in cells]
            name = values[0].strip("* ") if values else ""
            attrs = {}
            for h, v in zip(headers[1:], values[1:]):
                attrs[h] = v
            description = "; ".join(f"{k}: {v}" for k, v in attrs.items() if v)
            entries.append({
                "name": name,
                "description": description,
                "links": [],
                "attributes": attrs,
                "category": "CAD tools",
                "categorySlug": "cad-tools",
            })
    return entries


def main():
    all_entries = []

    for filename, (label, slug) in CATEGORY_MAP.items():
        path = SRC_DIR / filename
        if not path.exists():
            print(f"  [skip] {filename} not found at {path}")
            continue
        entries = parse_standard_file(path, label, slug)
        print(f"  {filename}: {len(entries)} entries")
        all_entries.extend(entries)

    cad_path = SRC_DIR / CAD_FILE
    if cad_path.exists():
        cad_entries = parse_cad_file(cad_path)
        print(f"  {CAD_FILE}: {len(cad_entries)} entries")
        all_entries.extend(cad_entries)

    for i, e in enumerate(all_entries):
        e["id"] = i

    out_path = OUT_DIR / "entries.json"
    out_path.write_text(json.dumps(all_entries, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWrote {len(all_entries)} total entries to {out_path}")

    categories = sorted({e["category"] for e in all_entries})
    print("Categories:", categories)


if __name__ == "__main__":
    main()
